### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by codekoala** [Bahus/uwsgi_tasks#1]
There is a print statement in setup.py that could easily be converted to a print function to help get this installable for Python 3. Additionally, some of the actual code includes things like `u'...'` and references to `basestring`.

I'll try to find time to work on these things in my fork.

**Comment by Bahus** [comment]
Hello! Some good news here - I'm going to add Python 3.4 support this weekend.

**Comment by codekoala** [comment]
Ah, fantastic! Thank you :)

**Comment by Bahus** [comment]
Release 0.4.3 is on pypi, tests passed on Python 3.4. If there are any issues, please let me know. Thank you.

**Comment by codekoala** [comment]
Thanks for this! I'm going to try playing with it today
