### ISSUE TITLE
spooler error on py3.6 with priority defined

### ISSUE THREAD

**Issue by slumtrimpet** [Bahus/uwsgi_tasks#11]
Calling a spooled method declared with a decorator:

`@task(executor=TaskExecutor.SPOOLER, priority=2)`

Throws error:

```
File "/apps/pocket-e/003/env/live/lib/python3.6/site-packages/uwsgi_tasks/tasks.py" in __call__
  624.         task.execute_async()

File "/apps/pocket-e/003/env/live/lib/python3.6/site-packages/uwsgi_tasks/tasks.py" in execute_async
  357.         return uwsgi.spool(self.get_message_content())

Exception Type: ValueError
Exception Value: spooler callable dictionary must contains only bytes
```

Inspecting the payload passed to uwsgi.spool() method:

```
{b'function_name': b'sentry.tasks.spooled_process_setup_data', b'args': b'\x80\x03K\x01\x85q\x00.', b'kwargs': b'\x80\x03}q\x00.', b'setup': b'\x80\x03}q\x00(X\x08\x00\x00\x00priorityq\x01K\x02X\x0b\x00\x00\x00working_dirq\x02X\x1e\x00\x00\x00/apps/pocket-e/003/pocketServeq\x03X\x0b\x00\x00\x00retry_countq\x04K\x00u.', b'priority': 2}
```

Note value of 'priority' is straight int here and not encoded bytes.

Adding the following at line 338 in tasks.py fixes the issue (but I'm not super happy with that hack fix so feel free to do it smarter please...):

```
                if isinstance(s, int):
                    return bytes([s])
```

**Comment by slumtrimpet** [comment]
Actually... maybe I'm being a dumb dumb.  Do you not accept syntax:

```
@task(executor=TaskExecutor.SPOOLER, priority=2)
```

to define the priority to pass with the spooler?

**Comment by Bahus** [comment]
Hi, thank you for reporting, but `priority` parameter should be a string since it's used internally by uwsgi to create a directory with the same name, see docs https://uwsgi-docs.readthedocs.io/en/latest/Spooler.html#priorities.

So, you may specify a priority like this `priority="2"`.

**Comment by slumtrimpet** [comment]
Gotcha, thanks for the reply.  Love the package.  👍
