### ISSUE TITLE
@task decorator on class method?

### ISSUE THREAD

**Issue by dogproblems** [Bahus/uwsgi_tasks#13]
Is this possible? I haven't been able to make it work, whether the method is static or not.
The task method:
```
class UserUploadImageEngine:
    @task
    @staticmethod
    def doerrand(errand_uid, src_drops)
        #do some work
```
The calling context:
```
UserUploadImageEngine.doerrand(errand_uid, src_drops)
```
The error message:
```
TypeError: <lambda>() takes 1 positional argument but 2 were given
```
If I just comment out the `@task` line in the first code block, it works fine (but not asynchronously, of course)

**Comment by Bahus** [comment]
Hi!, such feature is not implemented yet, only module level functions are supported by `@task` decorator.

**Comment by dogproblems** [comment]
Hi, thanks for responding so quickly!
It shouldn't be a problem to alter my code to allow for this - the method is already static.
I just wanted to make sure I wasn't doing something dumb...
