### ISSUE TITLE
retry_count is ignored

### ISSUE THREAD

**Issue by bob1de** [Bahus/uwsgi_tasks#18]
Hi,

While using this handsome library, I noticed that the retry_count parameter passed to `uwsgi_tasks.task()` is only respected with `spooler_return=False`.

This task:

```
import uwsgi_tasks

@uwsgi_tasks.task(executor=uwsgi_tasks.TaskExecutor.SPOOLER, spooler_return=True, retry_count=2, retry_timeout=10)
def test_task():
    return uwsgi_tasks.SPOOL_RETRY
```

is executed infinitely.

However, according to this from the README:

> retry_count - how many times spooler should repeat the task if it returns SPOOL_RETRY code, implies spooler_return=True.

I assumed passing `spooler_return=True` together with `retry_count` would make no difference. So how is it supposed to be? Should the README be changed to "This parameter doesn't work together with `spooler_return=True`" or is the logic wrong and retry_cound should indeed only work with `spooler_return=True`?

Best regards
Robert

**Comment by Bahus** [comment]
Hi, I understand that it's pretty late, but you could check the behaviour in the code:

https://github.com/Bahus/uwsgi_tasks/blob/708643db5294178a2f238fc741ac29238280e84f/uwsgi_tasks/tasks.py#L383-L391

If you set `spooler_return` to `True` then all `retry_*` parameters are not applied at all, so you should choose the approach: either to use `spooler_return=True` and then return `SPOOL_<SOMETHING>` from the task OR use `retry_<something>` parameters and return `SPOOL_RETRY` from the task.

**Comment by Bahus** [comment]
Changed docs, to avoid confusion in the future. Thanks!
