### ISSUE TITLE
Timer limit of 64 hit

### ISSUE THREAD

**Issue by yatahaze** [Bahus/uwsgi_tasks#19]
I've been developing with this for a while, but I had no idea about the 64 timer limit. Is there a way around this? 

I know of the rbtimer decorator, but I'm not sure how to make use of it with uwsgi-tasks. (The readme even mentions red-black timers but I'm stuck.)

**Comment by Bahus** [comment]
Hi, what kind of "64 timer limit" do you mean? Total number of timers? What kind of task are you trying to solve?

**Comment by yatahaze** [comment]
I've been creating many timers for the project I'm working on, and suddenly realized there is actually a limit in uwsgi as to how many times you can declare a timer. 

Turns out there's an easy fix by just using less timers and running multiple functions inside. I just had a mini panic attack that I wouldn't be able to create any new timers and my project design was flawed, but that's okay now :)

I heard that uwsgi has an rbtimer decorator that could be used to make unlimited timers, I'm not sure if that can be added to this project. But also not necessary since I found a workaround.
