### ISSUE TITLE
load_function seems to fail for a django app

### ISSUE THREAD

**Issue by chokosabe** [Bahus/uwsgi_tasks#4]
Decorator:
@task(executor=TaskExecutor.SPOOLER)

Error:
ImportError: Failed to import "channel.helpers.update_redis_channels" - No module named helpers
    raise ImportError('Failed to import "{}" - {}'.format(dotted_path, ex))

The same function called directly from code without the decorator works fine...

example.ini looks like this:
gid = root
chdir = /app_home_dir
socket = 127.0.0.1:3000
wsgi-file = app/wsgi.py
processes = 8
threads = 4
env = DJANGO_SETTINGS_MODULE=app.settings
logto = /var/log/uwsgi/%n.log
# module = app.wsgi:application

harakiri = 20
buffer-size = 65535
vacuum = True
# thunder-lock = True

pcre = True
max-requests = 5000

py-auto-reload = 3
# Spooling

spooler-import = /spooler_task_file.py 
spooler-processes = 4
spooler = /spooler_task_dir

Tracked it down to this call:

uwsgi_tasks.tasks.load_function

def load_function(func_name):
    func = getattr(saved_tasks, func_name, None)
    if func:
        return func
    return import_by_path(func_name)

import_by_path doesn't seem to find anything. Any reason this might be? Any way to debug this?

Thanks.

**Comment by Bahus** [comment]
Hi! Is it reproducible with the 0.6 version of uwsgi_tasks?
Please see my comment here: https://github.com/Bahus/uwsgi_tasks/issues/3#issuecomment-124918552
