### ISSUE TITLE
Specify timer args at call-time

### ISSUE THREAD

**Issue by thinkwelltwd** [Bahus/uwsgi_tasks#5]
Hi Bahus! I'd like to use your module in my django site, and I need to be able to call Timers with Seconds and Iterations based on feedback from the user. 

In reading your docs, I'm not sure how to accomplish that. Seems like you can only specify args when defining the timer rather than calling it. Is that correct? Or am I missing something?

Regards.

**Comment by Bahus** [comment]
Hello, @thinkwelldesigns! I have updated task introspection API in new release 0.6.4 and described the use-case in documentation https://github.com/Bahus/uwsgi_tasks#changing-task-configuration-before-execution.

Please keep in mind that it's not possible to find out if timer is started or stopped, thus every time an user opens page (Django view) new timer is activated. Good idea is to save information about users and their timers to separate storage to avoid duplicates.

**Comment by thinkwelltwd** [comment]
Now that looks great! Let me take it for a spin... Thanks for the quick response!
