### ISSUE TITLE
Spooler fails if message is too long

### ISSUE THREAD

**Issue by miszczu** [Bahus/uwsgi_tasks#7]
In SpoolerTask, when message is too long, args and kwargs parameters are passed in body parameter, which is ok. 
```python
if len(repr(message_dict)) >= UWSGI_MAXIMUM_MESSAGE_SIZE:
   # message too long for spooler - we have to use `body` parameter
   message_dict = base_message_dict
   message_dict['body'] = pickle.dumps({
      'args': self.args,
      'kwargs': self.kwargs,
})
```
The problem is that the message is not cleaned from original args/kwargs params (`message_dict['args']` and `message_dict['kwargs']`), and in the result these are not encoded and passed to `uwsgi.spool` function.
In the end `uwsgi.spool` fails with 
> ValueError: spooler callable dictionary must contains only bytes.

**Comment by Bahus** [comment]
Thank you for reporting the issue, but I don't see any problem here actually:

```python
# here we are making copy of base_message_dict, so when we change message_dict this
# do not affect base_message_dict at all, so base_message_dict does not contain args and kwargs
message_dict = base_message_dict.copy()
message_dict.update({
    'args': pickle.dumps(self.args),
    'kwargs': pickle.dumps(self.kwargs)
})
```

```python
# in case of huge args/kwargs size we reuse base_message_dict, 
# which does not contain args,kwargs as show above.
if len(repr(message_dict)) >= UWSGI_MAXIMUM_MESSAGE_SIZE:
    # message too long for spooler - we have to use `body` parameter
    message_dict = base_message_dict
    message_dict['body'] = pickle.dumps({
        'args': self.args,
        'kwargs': self.kwargs,
    })
```
And as I can see `message_dict` is totally replaced in the lines above.
Could you please clarify where is my reasoning incorrect?

**Comment by miszczu** [comment]
It actually does contain unpickled args and kwargs from the beginning:
```python
    def get_message_content(self):
        base_message_dict = self.__getstate__()
        (...)

    def __getstate__(self):
        return {
            'function_name': self.function_name,
            'args': self.args,
            'kwargs': self.kwargs,
            'setup': self.setup,
        }
```

In a pull request that I posted a while back (#8), I've proposed the fix that was simplest for me to prepare, but maybe it would be a good idea to do some larger changes so the flow is easier to read. 
There is also a regression test that fails without the rest of the changes.

**Comment by almussel** [comment]
I'm running into this same error when `message_dict` is larger than 64kb.

**Comment by Bahus** [comment]
@miszczu @almussel thank you, I have release a new version on pypi (0.7.2), so feel free to use it. 
But I'm still curious why do you use so huge messages?

**Comment by Bahus** [comment]
Closed because of inactivity.
